
// This object is used to print out pretties columns headers in the CSV
// When using the CSV writer, it has to be an array, where each element 
// represents a row

const csv_header = [
    { id: 'save_time', title: 'Save Time' },
    { id: 'voyage', title: 'Voyage' },
    { id: 'sheet', title: 'Sheet' },
    { id: 'date', title: 'Date' },
    { id: 'analyst', title: 'Analyst' },
    { id: 'file', title: 'File' },

    { id: 'pre_analysis_comments', title: 'Pre-Analysis Comments' },

    { id: 'air_valve', title: 'Air Tubing Moved' },
    { id: 'mq_container', title: 'MQ Container Full' },
    { id: 'reagents_ran', title: 'Reagents Ran For 30 Mins' },
    { id: 'reagents_sufficient', title: 'Sufficient Reagents' },
    { id: 'correct_rack_file', title: 'Correct Rack File' },
    { id: 'daily_check_comment', title: 'Daily Check Comment' },
    { id: 'all_dailies_checked', title: 'All Daily Completed' },

    { id: 'silicate_colour', title: 'Silicate Colour' },
    { id: 'silicate_acid', title: 'Silicate Acid' },
    { id: 'stannous', title: 'Stannous' },
    { id: 'opa', title: 'OPA' },
    { id: 'nox_buffer', title: 'NOx Buffer' },
    { id: 'nox_colour', title: 'NOx Colour' },
    { id: 'phosphate_colour', title: 'Phosphate Colour' },
    { id: 'phosphate_acid', title: 'Phosphate Acid' },
    { id: 'reagent_comment', title: 'New Reagents Comment' },

    { id: 'rmns_1', title: 'RMNS 1 Used' },
    { id: 'rmns_1_used', title: 'RMNS 1 Lot' },
    { id: 'rmns_2', title: 'RMNS 2 Used' },
    { id: 'rmns_2_used', title: 'RMNS 2 Lot' },
    { id: 'rmns_3', title: 'RMNS 3 Used' },
    { id: 'rmns_3_used', title: 'RMNS 3 Lot' },
    { id: 'internal_standard', title: 'Internal Standard' },
    { id: 'lnsw_batch', title: 'LNSW Batch' },
    { id: 'standards_date', title: 'Standards Date' },
    { id: 'standards_numbers', title: 'Standard No.' },

    { id: 'chan_1_nut', title: 'Channel1 Nutrient' },
    { id: 'chan_1_reagent_baseline', title: 'Channel1 Reagent Baseline' },
    { id: 'chan_1_gain', title: 'Channel1 Gain' },
    { id: 'chan_1_base_offset', title: 'Channel1 Base Offset' },
    { id: 'chan_2_nut', title: 'Channel2 Nutrient' },
    { id: 'chan_2_reagent_baseline', title: 'Channel2 Reagent Baseline' },
    { id: 'chan_2_gain', title: 'Channel2 Gain' },
    { id: 'chan_2_base_offset', title: 'Channel2 Base Offset' },
    { id: 'chan_3_nut', title: 'Channel3 Nutrient' },
    { id: 'chan_3_reagent_baseline', title: 'Channel3 Reagent Baseline' },
    { id: 'chan_3_gain', title: 'Channel3 Gain' },
    { id: 'chan_3_base_offset', title: 'Channel3 Base Offset' },
    { id: 'chan_4_nut', title: 'Channel4 Nutrient' },
    { id: 'chan_4_reagent_baseline', title: 'Channel4 Reagent Baseline' },
    { id: 'chan_4_gain', title: 'Channel4 Gain' },
    { id: 'chan_4_base_offset', title: 'Channel4 Base Offset' },
    { id: 'chan_5_nut', title: 'Channel5 Nutrient' },
    { id: 'chan_5_reagent_baseline', title: 'Channel5 Reagent Baseline' },
    { id: 'chan_5_gain', title: 'Channel5 Gain' },
    { id: 'chan_5_base_offset', title: 'Channel5 Base Offset' },

    { id: 'cadmium_col_prep_date', title: 'Cd Col Prep Date' },
    { id: 'cadmium_col_active_date', title: 'Cd Col Active Date' },
    { id: 'cadmium_col_efficiency', title: 'Cd Col Efficiency' },
    { id: 'tray_protocol_checked', title: 'Tray Protocol Checked' },

    { id: 'start_time', title: 'Start Time' },
    { id: 'finish_time', title: 'Finish Time' },
    { id: 'start_pump_tubes', title: 'Time on PTubes Start' },
    { id: 'finish_pump_tubes', title: 'Time on PTubes Finish' },
    { id: 'start_lab_temp', title: 'Start Lab Temp' },
    { id: 'finish_lab_temp', title: 'Finish Lab Temp' },
    { id: 'rack_used', title: 'Rack Used' },

    { id: 'trace_checked', title: 'Trace Checked' },
    { id: 'trace_concerns', title: 'Trace Concerns' },

    { id: 'nox_calibrants', title: 'NOx Calibrants' },
    { id: 'nox_curve', title: 'NOx Curve Type' },
    { id: 'nox_calibrants_comment', title: 'NOx Calibrants Comment' },
    { id: 'nox_r_squared', title: 'NOx R Squared' },
    { id: 'nox_baseline', title: 'NOx Baseline' },
    { id: 'nox_drift', title: 'NOx Drift' },
    { id: 'nox_mdl', title: 'NOx MDLs' },
    { id: 'nox_duplicates', title: 'NOx Duplicates' },
    { id: 'nox_rmns_1', title: 'NOx RMNS 1' },
    { id: 'nox_rmns_2', title: 'NOx RMNS 2' },
    { id: 'nox_rmns_3', title: 'NOx RMNS 3' },
    { id: 'nox_sus_samples', title: 'NOx Suspect Samples' },

    { id: 'phosphate_calibrants', title: 'Phosphate Calibrants' },
    { id: 'phosphate_curve', title: 'Phosphate Curve Type' },
    { id: 'phosphate_calibrants_comment', title: 'Phosphate Calibrants Comment' },
    { id: 'phosphate_r_squared', title: 'Phosphate R Squared' },
    { id: 'phosphate_baseline', title: 'Phosphate Baseline' },
    { id: 'phosphate_drift', title: 'Phosphate Drift' },
    { id: 'phosphate_mdl', title: 'Phosphate MDLs' },
    { id: 'phosphate_duplicates', title: 'Phosphate Duplicates' },
    { id: 'phosphate_rmns_1', title: 'Phosphate RMNS 1' },
    { id: 'phosphate_rmns_2', title: 'Phosphate RMNS 2' },
    { id: 'phosphate_rmns_3', title: 'Phosphate RMNS 3' },
    { id: 'phosphate_sus_samples', title: 'Phosphate Suspect Samples' },

    { id: 'silicate_calibrants', title: 'Silicate Calibrants' },
    { id: 'silicate_curve', title: 'Silicate Curve Type' },
    { id: 'silicate_calibrants_comment', title: 'Silicate Calibrants Comment' },
    { id: 'silicate_r_squared', title: 'Silicate R Squared' },
    { id: 'silicate_baseline', title: 'Silicate Baseline' },
    { id: 'silicate_drift', title: 'Silicate Drift' },
    { id: 'silicate_mdl', title: 'Silicate MDLs' },
    { id: 'silicate_duplicates', title: 'Silicate Duplicates' },
    { id: 'silicate_rmns_1', title: 'Silicate RMNS 1' },
    { id: 'silicate_rmns_2', title: 'Silicate RMNS 2' },
    { id: 'silicate_rmns_3', title: 'Silicate RMNS 3' },
    { id: 'silicate_sus_samples', title: 'Silicate Suspect Samples' },

    { id: 'ammonia_calibrants', title: 'Ammonia Calibrants' },
    { id: 'ammonia_curve', title: 'Ammonia Curve Type' },
    { id: 'ammonia_calibrants_comment', title: 'Ammonia Calibrants Comment' },
    { id: 'ammonia_r_squared', title: 'Ammonia R Squared' },
    { id: 'ammonia_baseline', title: 'Ammonia Baseline' },
    { id: 'ammonia_drift', title: 'Ammonia Drift' },
    { id: 'ammonia_mdl', title: 'Ammonia MDLs' },
    { id: 'ammonia_duplicates', title: 'Ammonia Duplicates' },
    { id: 'ammonia_rmns_1', title: 'Ammonia RMNS 1' },
    { id: 'ammonia_rmns_2', title: 'Ammonia RMNS 2' },
    { id: 'ammonia_rmns_3', title: 'Ammonia RMNS 3' },
    { id: 'ammonia_sus_samples', title: 'Ammonia Suspect Samples' },

    { id: 'nitrite_calibrants', title: 'Nitrite Calibrants' },
    { id: 'nitrite_curve', title: 'Nitrite Curve Type' },
    { id: 'nitrite_calibrants_comment', title: 'Nitrite Calibrants Comment' },
    { id: 'nitrite_r_squared', title: 'Nitrite R Squared' },
    { id: 'nitrite_baseline', title: 'Nitrite Baseline' },
    { id: 'nitrite_drift', title: 'Nitrite Drift' },
    { id: 'nitrite_mdl', title: 'Nitrite MDLs' },
    { id: 'nitrite_duplicates', title: 'Nitrite Duplicates' },
    { id: 'nitrite_rmns_1', title: 'Nitrite RMNS 1' },
    { id: 'nitrite_rmns_2', title: 'Nitrite RMNS 2' },
    { id: 'nitrite_rmns_3', title: 'Nitrite RMNS 3' },
    { id: 'nitrite_sus_samples', title: 'Nitrite Suspect Samples' },

    { id: 'review_person', title: 'Review Person' },
    { id: 'review_date', title: 'Review Date' },
    { id: 'review_outcome', title: 'Review Outcome' },
    { id: 'review_comment', title: 'Review Comment' },

    { id: 'samples_1', title: 'Samples 1' },
    { id: 'samples_condition_1', title: 'Samples 1 Condition' },
    { id: 'samples_comment_1', title: 'Samples 1 Comment' },

    { id: 'samples_2', title: 'Samples 2' },
    { id: 'samples_condition_2', title: 'Samples 2 Condition' },
    { id: 'samples_comment_2', title: 'Samples 2 Comment' },

    { id: 'samples_3', title: 'Samples 3' },
    { id: 'samples_condition_3', title: 'Samples 3 Condition' },
    { id: 'samples_comment_3', title: 'Samples 3 Comment' }
];

// This object is iterated through to collect all the form data
// and format it properly for the csv writer, so it matches the colunms
const output_name_object = {
        save_time: 0,
        voyage: 'voyage_name',
        sheet: 'sheet_number',
        date: 'date',
        analyst: 'analyst',
        file: 'file_name',

        pre_analysis_comments: 'pre_analysis_comments',

        air_valve: 'air_valve',
        mq_container: 'mq_cont',
        reagents_ran: 'reagents_ran',
        reagents_sufficient: 'reagents_sufficient',
        correct_rack_file: 'correct_rack_file',
        daily_check_comment: 'daily_check_comments',
        all_dailies_checked: 'all_daily_checked',

        silicate_colour: 'silicate_colour',
        silicate_acid: 'silicate_acid',
        stannous: 'stannous',
        opa: 'opa',
        nox_buffer: 'nox_buffer',
        nox_colour: 'nox_colour',
        phosphate_colour: 'phosphate_colour',
        phosphate_acid: 'phosphate_acid',
        reagent_comment: 'reagent_comments',

        rmns_1: 'rmns_1',
        rmns_1_used: 'rmns_1_used',
        rmns_2: 'rmns_2',
        rmns_2_used: 'rmns_2_used',
        rmns_3: 'rmns_3',
        rmns_3_used: 'rmns_3_used',
        internal_standard: 'internal_standard',
        lnsw_batch: 'lnsw_batch',
        standards_date: 'standards_date',
        standards_numbers: 'standards_numbers',

        chan_1_nut: 'channel_1_nutrient',
        chan_1_reagent_baseline: 'channel_1_reagent_baseline',
        chan_1_gain: 'channel_1_gain',
        chan_1_base_offset: 'channel_1_base_offset',
        chan_2_nut: 'channel_2_nutrient',
        chan_2_reagent_baseline: 'channel_2_reagent_baseline',
        chan_2_gain: 'channel_2_gain',
        chan_2_base_offset: 'channel_2_base_offset',
        chan_3_nut: 'channel_3_nutrient',
        chan_3_reagent_baseline: 'channel_3_reagent_baseline',
        chan_3_gain: 'channel_3_gain',
        chan_3_base_offset: 'channel_3_base_offset',
        chan_4_nut: 'channel_4_nutrient',
        chan_4_reagent_baseline: 'channel_4_reagent_baseline',
        chan_4_gain: 'channel_4_gain',
        chan_4_base_offset: 'channel_4_base_offset',
        chan_5_nut: 'channel_5_nutrient',
        chan_5_reagent_baseline: 'channel_5_reagent_baseline',
        chan_5_gain: 'channel_5_gain',
        chan_5_base_offset: 'channel_5_base_offset',

        cadmium_col_prep_date: 'cadmium_column_prep_date',
        cadmium_col_active_date: 'cadmium_column_activate_date',
        cadmium_col_efficiency: 'cadmium_column_efficiency',

        tray_protocol_checked: 'tray_protocol_checked',
        start_time: 'start_time',
        finish_time: 'finish_time',
        start_pump_tubes: 'start_pump_tube_hours',
        finish_pump_tubes: 'finish_pump_tube_hours',
        start_lab_temp: 'start_lab_temperature',
        finish_lab_temp: 'finish_lab_temperature',

        rack_used: 'rack_file_used',
        trace_checked: 'trace_checked',
        trace_concerns: 'trace_concerns',

        nox_calibrants: 'nox_calibrants',
        nox_curve: 'nox_curve',
        nox_calibrants_comment: 'nox_calibrants_comments',
        nox_r_squared: 'nox_r_squared',
        nox_baseline: 'nox_baseline',
        nox_drift: 'nox_drift',
        nox_mdl: 'nox_mdl',
        nox_duplicates: 'nox_duplicates',
        nox_rmns_1: 'nox_rmns_1',
        nox_rmns_2: 'nox_rmns_2',
        nox_rmns_3: 'nox_rmns_3',
        nox_sus_samples: 'nox_suspect_samples',

        phosphate_calibrants: 'phosphate_calibrants',
        phosphate_curve: 'phosphate_curve',
        phosphate_calibrants_comment: 'phosphate_calibrants_comments',
        phosphate_r_squared: 'phosphate_r_squared',
        phosphate_baseline: 'phosphate_baseline',
        phosphate_drift: 'phosphate_drift',
        phosphate_mdl: 'phosphate_mdl',
        phosphate_duplicates: 'phosphate_duplicates',
        phosphate_rmns_1: 'phosphate_rmns_1',
        phosphate_rmns_2: 'phosphate_rmns_2',
        phosphate_rmns_3: 'phosphate_rmns_3',
        phosphate_sus_samples: 'phosphate_suspect_samples',

        silicate_calibrants: 'silicate_calibrants',
        silicate_curve: 'silicate_curve',
        silicate_calibrants_comment: 'silicate_calibrants_comments',
        silicate_r_squared: 'silicate_r_squared',
        silicate_baseline: 'silicate_baseline',
        silicate_drift: 'silicate_drift',
        silicate_mdl: 'silicate_mdl',
        silicate_duplicates: 'silicate_duplicates',
        silicate_rmns_1: 'silicate_rmns_1',
        silicate_rmns_2: 'silicate_rmns_2',
        silicate_rmns_3: 'silicate_rmns_3',
        silicate_sus_samples: 'silicate_suspect_samples',

        ammonia_calibrants: 'ammonia_calibrants',
        ammonia_curve: 'ammonia_curve',
        ammonia_calibrants_comment: 'ammonia_calibrants_comments',
        ammonia_r_squared: 'ammonia_r_squared',
        ammonia_baseline: 'ammonia_baseline',
        ammonia_drift: 'ammonia_drift',
        ammonia_mdl: 'ammonia_mdl',
        ammonia_duplicates: 'ammonia_duplicates',
        ammonia_rmns_1: 'ammonia_rmns_1',
        ammonia_rmns_2: 'ammonia_rmns_2',
        ammonia_rmns_3: 'ammonia_rmns_3',
        ammonia_sus_samples: 'ammonia_suspect_samples',

        nitrite_calibrants: 'nitrite_calibrants',
        nitrite_curve: 'nitrite_curve',
        nitrite_calibrants_comment: 'nitrite_calibrants_comments',
        nitrite_r_squared: 'nitrite_r_squared',
        nitrite_baseline: 'nitrite_baseline',
        nitrite_drift: 'nitrite_drift',
        nitrite_mdl: 'nitrite_mdl',
        nitrite_duplicates: 'nitrite_duplicates',
        nitrite_rmns_1: 'nitrite_rmns_1',
        nitrite_rmns_2: 'nitrite_rmns_2',
        nitrite_rmns_3: 'nitrite_rmns_3',
        nitrite_sus_samples: 'nitrite_suspect_samples',

        review_person: 'review_person',
        review_date: 'review_date',
        review_outcome: 'review_outcome',
        review_comment: 'review_comments',

        samples_1: 'samples_1',
        samples_condition_1: 'samples_condition_1',
        samples_comment_1: 'samples_comment_1',

        samples_2: 'samples_2',
        samples_condition_2: 'samples_condition_2',
        samples_comment_2: 'samples_comment_2',

        samples_3: 'samples_3',
        samples_condition_3: 'samples_condition_3',
        samples_comment_3: 'samples_comment_3',

    };

// For when the data is loaded in, the header converter object is 
// used to conver the pretty CSV column headers to the HTML form IDs
const header_converter = {
    save_time: 'Save Time',
    voyage_name: 'Voyage',
    sheet_number: 'Sheet',
    date: 'Date',
    analyst: 'Analyst',
    file_name: 'File',

    pre_analysis_comments: 'Pre-Analysis Comments',

    air_valve: 'Air Tubing Moved',
    mq_cont: 'MQ Container Full',
    reagents_ran: 'Reagents Ran For 30 Mins',
    reagents_sufficient: 'Sufficient Reagents',
    correct_rack_file: 'Correct Rack File',
    daily_check_comments: 'Daily Check Comment',
    all_daily_checked: 'All Daily Completed',

    silicate_colour: 'Silicate Colour',
    silicate_acid: 'Silicate Acid',
    stannous: 'Stannous',
    opa: 'OPA',
    nox_buffer: 'NOx Buffer',
    nox_colour: 'NOx Colour',
    phosphate_colour: 'Phosphate Colour',
    phosphate_acid: 'Phosphate Acid',
    reagent_comments: 'New Reagents Comment',

    rmns_1: 'RMNS 1 Used',
    rmns_1_used: 'RMNS 1 Lot',
    rmns_2: 'RMNS 2 Used',
    rmns_2_used: 'RMNS 2 Lot',
    rmns_3: 'RMNS 3 Used',
    rmns_3_used: 'RMNS 3 Lot',
    internal_standard: 'Internal Standard',
    lnsw_batch: 'LNSW Batch',
    standards_date: 'Standards Date',
    standards_numbers: 'Standard No.',

    channel_1_nutrient: 'Channel1 Nutrient',
    channel_1_reagent_baseline: 'Channel1 Reagent Baseline',
    channel_1_gain: 'Channel1 Gain',
    channel_1_base_offset: 'Channel1 Base Offset',
    channel_2_nutrient: 'Channel2 Nutrient',
    channel_2_reagent_baseline: 'Channel2 Reagent Baseline',
    channel_2_gain: 'Channel2 Gain',
    channel_2_base_offset: 'Channel2 Base Offset',
    channel_3_nutrient: 'Channel3 Nutrient',
    channel_3_reagent_baseline: 'Channel3 Reagent Baseline',
    channel_3_gain: 'Channel3 Gain',
    channel_3_base_offset: 'Channel3 Base Offset',
    channel_4_nutrient: 'Channel4 Nutrient',
    channel_4_reagent_baseline: 'Channel4 Reagent Baseline',
    channel_4_gain: 'Channel4 Gain',
    channel_4_base_offset: 'Channel4 Base Offset',
    channel_5_nutrient: 'Channel5 Nutrient',
    channel_5_reagent_baseline: 'Channel5 Reagent Baseline',
    channel_5_gain: 'Channel5 Gain',
    channel_5_base_offset: 'Channel5 Base Offset',

    cadmium_column_prep_date: 'Cd Col Prep Date',
    cadmium_column_activate_date: 'Cd Col Active Date',
    cadmium_column_efficiency: 'Cd Col Efficiency',
    tray_protocol_checked: 'Tray Protocol Checked',

    start_time: 'Start Time',
    finish_time: 'Finish Time',
    start_pump_tube_hours: 'Time on PTubes Start',
    finish_pump_tube_hours: 'Time on PTubes Finish',
    start_lab_temperature: 'Start Lab Temp',
    finish_lab_temperature: 'Finish Lab Temp',

    rack_file_used: 'Rack Used',
    trace_checked: 'Trace Checked',
    trace_concerns: 'Trace Concerns',

    nox_calibrants: 'NOx Calibrants',
    nox_curve: 'NOx Curve Type',
    nox_calibrants_comments: 'NOx Calibrants Comment',
    nox_r_squared: 'NOx R Squared',
    nox_baseline: 'NOx Baseline',
    nox_drift: 'NOx Drift',
    nox_mdl: 'NOx MDLs',
    nox_duplicates: 'NOx Duplicates',
    nox_rmns_1: 'NOx RMNS 1',
    nox_rmns_2: 'NOx RMNS 2',
    nox_rmns_3: 'NOx RMNS 3',
    nox_suspect_samples: 'NOx Suspect Samples',

    phosphate_calibrants: 'Phosphate Calibrants',
    phosphate_curve: 'Phosphate Curve Type',
    phosphate_calibrants_comments: 'Phosphate Calibrants Comment',
    phosphate_r_squared: 'Phosphate R Squared',
    phosphate_baseline: 'Phosphate Baseline',
    phosphate_drift: 'Phosphate Drift',
    phosphate_mdl: 'Phosphate MDLs',
    phosphate_duplicates: 'Phosphate Duplicates',
    phosphate_rmns_1: 'Phosphate RMNS 1',
    phosphate_rmns_2: 'Phosphate RMNS 2',
    phosphate_rmns_3: 'Phosphate RMNS 3',
    phosphate_suspect_samples: 'Phosphate Suspect Samples',

    silicate_calibrants: 'Silicate Calibrants',
    silicate_curve: 'Silicate Curve Type',
    silicate_calibrants_comments: 'Silicate Calibrants Comment',
    silicate_r_squared: 'Silicate R Squared',
    silicate_baseline: 'Silicate Baseline',
    silicate_drift: 'Silicate Drift',
    silicate_mdl: 'Silicate MDLs',
    silicate_duplicates: 'Silicate Duplicates',
    silicate_rmns_1: 'Silicate RMNS 1',
    silicate_rmns_2: 'Silicate RMNS 2',
    silicate_rmns_3: 'Silicate RMNS 3',
    silicate_suspect_samples: 'Silicate Suspect Samples',

    ammonia_calibrants: 'Ammonia Calibrants',
    ammonia_curve: 'Ammonia Curve Type',
    ammonia_calibrants_comments: 'Ammonia Calibrants Comment',
    ammonia_r_squared: 'Ammonia R Squared',
    ammonia_baseline: 'Ammonia Baseline',
    ammonia_drift: 'Ammonia Drift',
    ammonia_mdl: 'Ammonia MDLs',
    ammonia_duplicates: 'Ammonia Duplicates',
    ammonia_rmns_1: 'Ammonia RMNS 1',
    ammonia_rmns_2: 'Ammonia RMNS 2',
    ammonia_rmns_3: 'Ammonia RMNS 3',
    ammonia_suspect_samples: 'Ammonia Suspect Samples',

    nitrite_calibrants: 'Nitrite Calibrants',
    nitrite_curve: 'Nitrite Curve Type',
    nitrite_calibrants_comments: 'Nitrite Calibrants Comment',
    nitrite_r_squared: 'Nitrite R Squared',
    nitrite_baseline: 'Nitrite Baseline',
    nitrite_drift: 'Nitrite Drift',
    nitrite_mdl: 'Nitrite MDLs',
    nitrite_duplicates: 'Nitrite Duplicates',
    nitrite_rmns_1: 'Nitrite RMNS 1',
    nitrite_rmns_2: 'Nitrite RMNS 2',
    nitrite_rmns_3: 'Nitrite RMNS 3',
    nitrite_suspect_samples: 'Nitrite Suspect Samples',

    review_person: 'Review Person',
    review_date: 'Review Date',
    review_outcome: 'Review Outcome',
    review_comments: 'Review Comment',

    samples_1: 'Samples 1',
    samples_condition_1: 'Samples 1 Condition',
    samples_comment_1: 'Samples 1 Comment',

    samples_2: 'Samples 2',
    samples_condition_2: 'Samples 2 Condition',
    samples_comment_2: 'Samples 2 Comment',

    samples_3: 'Samples 3',
    samples_condition_3: 'Samples 3 Condition',
    samples_comment_3: 'Samples 3 Comment',

};

// export in node conventions
module.exports = {csv_header, output_name_object, header_converter};