# name of your github action
name: Build
# this will help you specify where to run 
on:
  push:
    branches:
      - master

jobs:
  build_on_win:
    name: Create Executable
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1    
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: Install Node dependencies
      run: |
        npm install
        ls ./
    
    - name: Build Executable
      run: |
        electron-packager AppDir AppName --platform=win32 --arch=ia32 --electronVersion=1.4.13 --app-version=1.0.0 --build-version=2.0.0 --icon=./assets/favicon.ico --prune=false --overwrite=true && electron ./package.js
         
    - name: see directory
      run: ls
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build_contents
        path: dist
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: "Automatic Build"
        files: |
          ./dist/*.exe
